name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Увеличиваем таймаут для долгих сборок

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        tags: roblodev/comfyui-instagirl-v2.5:latest
        push: false
        outputs: type=docker,dest=/tmp/image.tar
      env:
        BUILDKIT_PROGRESS: plain  # Более читаемый вывод для логов

    - name: Test Docker image
      run: |
        docker load --input /tmp/image.tar
        docker images | grep comfyui-instagirl

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        tags: roblodev/comfyui-instagirl-v2.5:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
      env:
        BUILDKIT_PROGRESS: plain
